--- INSERTIONS ---
INSERT INTO personnage values(1 , 'Mario'           , 1 );
INSERT INTO personnage values(2 , 'Donkey Kong'     , 9 );
INSERT INTO personnage values(3 , 'Link'            , 3 );
INSERT INTO personnage values(4 , 'Samus'           , 5 );
INSERT INTO personnage values(5 , 'Dark Samus'      , 5 );
INSERT INTO personnage values(6 , 'Yoshi'           , 11);
INSERT INTO personnage values(7 , 'Kirby'           , 6 );
INSERT INTO personnage values(8 , 'Fox'             , 7 ); 
INSERT INTO personnage values(9 , 'Pikachu'         , 2 );
INSERT INTO personnage values(10, 'Luigi'           , 1 );
INSERT INTO personnage values(11, 'Ness'            , 10);
INSERT INTO personnage values(12, 'Captain Falcon'  , 12);
INSERT INTO personnage values(13, 'Jigglypuff'      , 2 );
INSERT INTO personnage values(14, 'Peach'           , 1 );
INSERT INTO personnage values(15, 'Daisy'           , 1 );
INSERT INTO personnage values(16, 'Bowser'          , 1 );
INSERT INTO personnage values(17, 'Ice Climbers'    , 13);
INSERT INTO personnage values(18, 'Sheik'           , 3 );
INSERT INTO personnage values(19, 'Zelda'           , 3 );
INSERT INTO personnage values(20, 'Dr. Mario'       , 1 );
INSERT INTO personnage values(21, 'Pichu'           , 2 );
INSERT INTO personnage values(22, 'Falco'           , 7 );
INSERT INTO personnage values(23, 'Marth'           , 4 );
INSERT INTO personnage values(24, 'Lucina'          , 4 );
INSERT INTO personnage values(25, 'Young Link'      , 3 );
INSERT INTO personnage values(26, 'Ganondorf'       , 3 );
INSERT INTO personnage values(27, 'Mewtwo'          , 2 );
INSERT INTO personnage values(28, 'Roy'             , 4 );
INSERT INTO personnage values(29, 'Chrom'           , 4 );
INSERT INTO personnage values(30, 'Mr. Game & Watch', 14);
INSERT INTO personnage values(31, 'Meta Knight'     , 6 );
INSERT INTO personnage values(32, 'Pit'             , 8 );
INSERT INTO personnage values(33, 'Dark Pit'        , 8 );
INSERT INTO personnage values(34, 'Zero Suit Samus' , 5 );
INSERT INTO personnage values(35, 'Wario'           , 15);
INSERT INTO personnage values(36, 'Snake'           , 16);
INSERT INTO personnage values(37, 'Ike'             , 4 );
INSERT INTO personnage values(38, 'Pokemon Trainer' , 2 );
INSERT INTO personnage values(39, 'Diddy Kong'      , 9 );
INSERT INTO personnage values(40, 'Lucas'           , 10);
INSERT INTO personnage values(41, 'Sonic'           , 17);
INSERT INTO personnage values(42, 'King Dedede'     , 6 );
INSERT INTO personnage values(43, 'Olimar'          , 18);
INSERT INTO personnage values(44, 'Lucario'         , 2 );
INSERT INTO personnage values(45, 'R.O.B'           , 19);
INSERT INTO personnage values(46, 'Toon Link'       , 3 );
INSERT INTO personnage values(47, 'Wolf'            , 7 );
INSERT INTO personnage values(48, 'Villager'        , 20);
INSERT INTO personnage values(49, 'Mega Man'        , 21);
INSERT INTO personnage values(50, 'Wii Fit Trainer' , 22);
INSERT INTO personnage values(51, 'Rosalina & Luma' , 1 );
INSERT INTO personnage values(52, 'Little Mac'      , 23);
INSERT INTO personnage values(53, 'Greninja'        , 2 );
INSERT INTO personnage values(54, 'Mii Brawler'     , 24);
INSERT INTO personnage values(55, 'Mii Swordfighter', 24);
INSERT INTO personnage values(56, 'Mii Gunner'      , 24);
INSERT INTO personnage values(57, 'Palutena'        , 8 );
INSERT INTO personnage values(58, 'Pac-Man'         , 25);
INSERT INTO personnage values(59, 'Robin'           , 4 );
INSERT INTO personnage values(60, 'Shulk'           , 26);
INSERT INTO personnage values(61, 'Bowser Jr.'      , 1 );
INSERT INTO personnage values(62, 'Duck Hunt'       , 27);
INSERT INTO personnage values(63, 'Ryu'             , 28);
INSERT INTO personnage values(64, 'Ken'             , 28);
INSERT INTO personnage values(65, 'Cloud'           , 29);
INSERT INTO personnage values(66, 'Corrin'          , 4 );
INSERT INTO personnage values(67, 'Bayonetta'       , 30);
INSERT INTO personnage values(68, 'Inkling'         , 31);
INSERT INTO personnage values(69, 'Ridley'          , 5 );
INSERT INTO personnage values(70, 'Simon'           , 32);
INSERT INTO personnage values(71, 'Richter'         , 32);
INSERT INTO personnage values(72, 'King K. Rool'    , 9 );
INSERT INTO personnage values(73, 'Isabelle'        , 20);
INSERT INTO personnage values(74, 'Incineroar'      , 2 );
INSERT INTO personnage values(75, 'Piranha Plant'   , 1 );
INSERT INTO personnage values(76, 'Joker'           , 33);
INSERT INTO personnage values(77, 'Hero'            , 34);
INSERT INTO personnage values(78, 'Banjo & Kazooie' , 35);
INSERT INTO personnage values(79, 'Terry'           , 36);
INSERT INTO personnage values(80, 'Byleth'          , 4 );
INSERT INTO personnage values(81, 'Min Min'         , 37);
INSERT INTO personnage values(82, 'Steve'           , 38);
INSERT INTO personnage values(83, 'Sephiroth'       , 29);
INSERT INTO personnage values(84, 'Pyra/Mythra'     , 26);
INSERT INTO personnage values(85, 'Kazuya'          , 39);
INSERT INTO personnage values(86, 'Sora'            , 40);