--- INSERTIONS ---
INSERT INTO franchise values(1,  'Super Mario'                  );
INSERT INTO franchise values(2,  'Pokemon'                      );
INSERT INTO franchise values(3,  'Zelda'                        );
INSERT INTO franchise values(4,  'Fire Emblem'                  );
INSERT INTO franchise values(5,  'Metroid'                      );
INSERT INTO franchise values(6,  'Kirby'                        );
INSERT INTO franchise values(7,  'Star Fox'                     );
INSERT INTO franchise values(8,  'Kid Icarus'                   );
INSERT INTO franchise values(9,  'Donkey Kong'                  );
INSERT INTO franchise values(10, 'Earthbound'                   );
INSERT INTO franchise values(11, 'Yoshi'                        );
INSERT INTO franchise values(12, 'F-Zero'                       );
INSERT INTO franchise values(13, 'Ice Climber'                  );
INSERT INTO franchise values(14, 'Game & Watch'                 );
INSERT INTO franchise values(15, 'WarioWare'                    );
INSERT INTO franchise values(16, 'Metal Gear'                   );
INSERT INTO franchise values(17, 'Sonic the Hedgehog'           );
INSERT INTO franchise values(18, 'Pikmin'                       );
INSERT INTO franchise values(19, 'Nintendo Entertainment System');
INSERT INTO franchise values(20, 'Animal Crossing'              );
INSERT INTO franchise values(21, 'Megaman'                      );
INSERT INTO franchise values(22, 'Wii Fit'                      );
INSERT INTO franchise values(23, 'Punch-Out'                    );
INSERT INTO franchise values(24, 'Mii'                          );
INSERT INTO franchise values(25, 'Pac-Man'                      );
INSERT INTO franchise values(26, 'Xenoblade'                    );
INSERT INTO franchise values(27, 'Duck Hunt'                    );
INSERT INTO franchise values(28, 'Street Fighter'               );
INSERT INTO franchise values(29, 'Final Fantasy'                );
INSERT INTO franchise values(30, 'Bayonetta'                    );
INSERT INTO franchise values(31, 'Splatoon'                     );
INSERT INTO franchise values(32, 'Castlevania'                  );
INSERT INTO franchise values(33, 'Persona'                      );
INSERT INTO franchise values(34, 'Dragon Quest'                 );
INSERT INTO franchise values(35, 'Banjo-Kazooie'                );
INSERT INTO franchise values(36, 'Fatal Fury'                   );
INSERT INTO franchise values(37, 'Arms'                         );
INSERT INTO franchise values(38, 'Minecraft'                    );
INSERT INTO franchise values(39, 'Tekken'                       );
INSERT INTO franchise values(40, 'Kingdom Hearts'               );