--- INSERTIONS ---
INSERT INTO personne values(1  , 'MKleo'         , 21, 'M', 'Mexique'    , 'T1'                 );
INSERT INTO personne values(2  , 'HungryBox'     , 29, 'F', 'Etats-Unis' , 'T1'                 );
INSERT INTO personne values(3  , 'Capitaine'     , 25, 'M', 'France'     , 'IUT'                );
INSERT INTO personne values(4  , 'Pacou'         , 42, 'F', 'France'     , 'IUT'                );
INSERT INTO personne values(5  , 'Gudrun'        , 20, 'M', 'France'     , 'Yggdrazil'          );
INSERT INTO personne values(6  , 'Akuma'         , 20, 'F', 'Angleterre' , 'Cipher'             );
INSERT INTO personne values(7  , 'Dany'          , 26, 'M', 'France'     , 'SQL'                );
INSERT INTO personne values(8  , 'Moqmoq'        , 14, 'M', 'Espagne'    , 'Pokegang'           );
INSERT INTO personne values(9  , 'Akvir'         , 62, 'F', 'France'     , 'Eco Smash'          );
INSERT INTO personne values(10 , 'Pherax'        , 24, 'F', 'Irlande'    , 'SKUIZI'             );
INSERT INTO personne values(11 , 'Maximum Propum', 24, 'M', 'Suède'      , 'ArmadaTeam'         );
INSERT INTO personne values(12 , 'Moquouss'      , 18, 'M', 'France'     , 'Yggdrazil'          );
INSERT INTO personne values(13 , 'Joyca'         , 26, 'M', 'Ecosse'     , 'Rhinoshield'        );
INSERT INTO personne values(14 , 'Glutonny'      , 27, 'M', 'France'     , 'WaaaaTeam'          );
INSERT INTO personne values(15 , 'Pataploup'     , 19, 'M', 'Etats-Unis' , 'Xiaomi'             );
INSERT INTO personne values(16 , 'Jeff'          , 44, 'M', 'Etats-Unis' , 'Samsung'            );
INSERT INTO personne values(17 , 'Armada'        , 26, 'M', 'Suisse'     , 'Iphone'             );
INSERT INTO personne values(18 , 'Mango'         , 34, 'M', 'Etats-Unis' , 'Sony'               );
INSERT INTO personne values(19 , 'MangoBanana'   , 35, 'F', 'Etats-Unis' , 'Sony'               );
INSERT INTO personne values(20 , 'Mew2King'      , 28, 'F', 'Iran'       , 'Microsoft'          );
INSERT INTO personne values(21 , 'JeanPeuPlu'    , 26, 'M', 'Iran'       , 'Microsoft'          );
INSERT INTO personne values(22 , 'Leffen'        , 24, 'F', 'Etats-Unis' , 'Bethesda'           );
INSERT INTO personne values(23 , 'Tayly'         , 28, 'M', 'Listembourg', 'Listembourg'        );
INSERT INTO personne values(24 , 'Dusty'         , 23, 'M', 'Etats-Unis' , 'Gouvernement'       );
INSERT INTO personne values(25 , 'Craft'         , 28, 'M', 'Iran'       , 'Nintendo'           );
INSERT INTO personne values(26 , 'Skuizi'        , 28, 'M', 'France'     , 'Squeezie'           );
INSERT INTO personne values(27 , 'Kiyu'          , 24, 'M', 'France'     , 'SPA'                );
INSERT INTO personne values(28 , 'Paulok'        , 14, 'M', 'Listembourg', 'Charal'             );
INSERT INTO personne values(29 , 'Laupok'        , 29, 'M', 'France'     , 'Sega'               );
INSERT INTO personne values(30 , 'Socko'         , 19, 'M', 'Listembourg', 'Samsung'            );
INSERT INTO personne values(31 , 'Kennedy'       , 28, 'M', 'Etats-Unis' , 'Gouvernement'       );
INSERT INTO personne values(32 , 'Florian'       , 20, 'F', 'France'     , 'Looping'            );
INSERT INTO personne values(33 , 'ArmadaJr'      , 24, 'F', 'Suède'      , 'Armada'             );
INSERT INTO personne values(34 , 'FilthyBox'     , 44, 'F', 'Mexique'    , 'Wespeed'            );
INSERT INTO personne values(35 , 'Pika1Queen'    , 21, 'F', 'Brésil'     , 'Hal Laboratory Inc.');
INSERT INTO personne values(36 , 'Appol'         , 25, 'M', 'Chine'      , 'Bandai Namco'       );
INSERT INTO personne values(37 , 'Son Jr'        , 35, 'M', 'Japon'      , 'Jump'               );
INSERT INTO personne values(38 , 'Rick'          , 42, 'M', 'Etats-Unis' , 'Cartoon Network'    );
INSERT INTO personne values(39 , 'Moonlight'     , 20, 'F', 'Angleterre' , 'SK Gaming'          );
INSERT INTO personne values(40 , 'Yde'           , 23, 'M', 'Suède'      , 'Tribe'              );
INSERT INTO personne values(41 , 'Fishou'        , 33, 'M', 'France'     , 'Solary'             );
INSERT INTO personne values(42 , 'Odemian'       , 27, 'M', 'France'     , 'Twitch'             );
INSERT INTO personne values(43 , 'Amko'          , 18, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(44 , 'Yurika'        , 22, 'F', 'Inde'       , 'Oreo'               );
INSERT INTO personne values(45 , 'Lolodrog'      , 23, 'M', 'France'     , 'Rhinoshield'        );
INSERT INTO personne values(46 , 'ChianRelou'    , 34, 'M', 'France'     , 'Rhinoshield'        );
INSERT INTO personne values(47 , 'Mily'          , 28, 'F', 'Etats-Unis' , 'In shape'           );
INSERT INTO personne values(48 , 'Koya'          , 18, 'M', 'Japon'      , 'Jump'               );
INSERT INTO personne values(49 , 'Russkiya'      , 25, 'F', 'Japon'      , 'Jump'               );
INSERT INTO personne values(50 , 'Gudrun'        , 20, 'M', 'France'     , 'Yggdrazil'          );
INSERT INTO personne values(51 , 'Swamey'        , 31, 'F', 'France'     , 'Yggdrazil'          );
INSERT INTO personne values(52 , 'Lix'           , 22, 'F', 'France'     , 'Yggdrazil'          );
INSERT INTO personne values(53 , 'Airika'        , 21, 'F', 'Angleterre' , 'Cipher'             );
INSERT INTO personne values(54 , 'Afton'         , 25, 'M', 'France'     , 'SQL'                );
INSERT INTO personne values(55 , 'Crouton'       , 22, 'M', 'France'     , 'SQL'                );
INSERT INTO personne values(56 , 'Shiron'        , 34, 'F', 'Espagne'    , 'Pokegang'           );
INSERT INTO personne values(57 , 'DraxEZ'        , 18, 'F', 'Espagne'    , 'Pokegang'           );
INSERT INTO personne values(58 , 'Deadlight'     , 20, 'M', 'Espagne'    , 'Pokegang'           );
INSERT INTO personne values(59 , 'Artemisa'      , 40, 'F', 'France'     , 'Eco Smash'          );
INSERT INTO personne values(60 , 'Hatsuko'       , 34, 'M', 'France'     , 'Eco Smash'          );
INSERT INTO personne values(61 , 'Kehba'         , 39, 'F', 'France'     , 'Eco Smash'          );
INSERT INTO personne values(62 , 'Menthys'       , 30, 'M', 'France'     , 'Eco Smash'          );
INSERT INTO personne values(63 , 'Callate'       , 32, 'F', 'Irlande'    , 'SKUIZI'             );
INSERT INTO personne values(64 , 'Kei'           , 23, 'F', 'Irlande'    , 'SKUIZI'             );
INSERT INTO personne values(65 , 'Mooon'         , 28, 'M', 'Suède'      , 'ArmadaTeam'         );
INSERT INTO personne values(66 , 'DimitryOS'     , 29, 'M', 'Suède'      , 'ArmadaTeam'         );
INSERT INTO personne values(67 , 'Relty'         , 28, 'F', 'Suède'      , 'ArmadaTeam'         );
INSERT INTO personne values(68 , 'Megumi'        , 19, 'F', 'Etats-Unis' , 'Xiaomi'             );
INSERT INTO personne values(69 , 'Nice'          , 18, 'F', 'Etats-Unis' , 'Xiaomi'             );
INSERT INTO personne values(70 , 'Rubby'         , 19, 'F', 'Etats-Unis' , 'Xiaomi'             );
INSERT INTO personne values(71 , 'Shinya'        , 34, 'M', 'Etats-Unis' , 'Samsung'            );
INSERT INTO personne values(72 , 'Feuj'          , 35, 'M', 'Etats-Unis' , 'Samsung'            );
INSERT INTO personne values(73 , 'Steffy'        , 32, 'M', 'Etats-Unis' , 'Samsung'            );
INSERT INTO personne values(74 , 'Snake'         , 20, 'M', 'Suisse'     , 'Iphone'             );
INSERT INTO personne values(75 , 'Trapzi'        , 19, 'M', 'Suisse'     , 'Iphone'             );
INSERT INTO personne values(76 , 'Utako'         , 41, 'M', 'Etats-Unis' , 'Sony'               );
INSERT INTO personne values(77 , 'Elo'           , 42, 'M', 'Etats-Unis' , 'Sony'               );
INSERT INTO personne values(78 , 'Winnie'        , 38, 'M', 'Iran'       , 'Microsoft'          );
INSERT INTO personne values(79 , 'Alphau'        , 41, 'M', 'Iran'       , 'Microsoft'          );
INSERT INTO personne values(80 , 'irony'         , 45, 'M', 'Iran'       , 'Microsoft'          );
INSERT INTO personne values(81 , 'Fundy'         , 24, 'M', 'Etats-Unis' , 'Bethesda'           );
INSERT INTO personne values(82 , 'Sapnap'        , 29, 'F', 'Etats-Unis' , 'Bethesda'           );
INSERT INTO personne values(83 , 'Dumzy'         , 21, 'F', 'Listembourg', 'Listembourg'        );
INSERT INTO personne values(84 , 'Duma'          , 20, 'F', 'Listembourg', 'Listembourg'        );
INSERT INTO personne values(85 , 'Squirrels'     , 19, 'M', 'Listembourg', 'Listembourg'        );
INSERT INTO personne values(86 , 'Xenon'         , 18, 'M', 'Listembourg', 'Listembourg'        );
INSERT INTO personne values(87 , 'Altirix'       , 43, 'M', 'Etats-Unis' , 'Gouvernement'       );
INSERT INTO personne values(88 , 'Bigdodab'      , 33, 'M', 'Etats-Unis' , 'Gouvernement'       );
INSERT INTO personne values(89 , 'Bush'          , 27, 'M', 'Iran'       , 'Nintendo'           );
INSERT INTO personne values(90 , 'Piralio'       , 27, 'F', 'Iran'       , 'Nintendo'           );
INSERT INTO personne values(91 , 'Falink'        , 29, 'F', 'Iran'       , 'Nintendo'           );
INSERT INTO personne values(92 , 'Jertzu'        , 21, 'M', 'France'     , 'Squeezie'           );
INSERT INTO personne values(93 , 'Tronberry'     , 18, 'M', 'France'     , 'Squeezie'           );
INSERT INTO personne values(94 , 'Mx'            , 47, 'M', 'France'     , 'SPA'                );
INSERT INTO personne values(95 , 'Volak'         , 46, 'M', 'France'     , 'SPA'                );
INSERT INTO personne values(96 , 'Volkzak'       , 49, 'M', 'France'     , 'SPA'                );
INSERT INTO personne values(97 , 'Zen'           , 19, 'M', 'Listembourg', 'Charal'             );
INSERT INTO personne values(98 , 'Bloodyvortex'  , 25, 'M', 'Listembourg', 'Charal'             );
INSERT INTO personne values(99 , 'Poot'          , 34, 'M', 'France'     , 'Sega'               );
INSERT INTO personne values(100, 'Frozen'        , 31, 'M', 'France'     , 'Sega'               );
INSERT INTO personne values(101, 'Florian'       , 33, 'F', 'France'     , 'Looping'            );
INSERT INTO personne values(102, 'Niemman'       , 38, 'F', 'Mexique'    , 'Wespeed'            );
INSERT INTO personne values(103, 'Shirli'        , 38, 'M', 'Mexique'    , 'Wespeed'            );
INSERT INTO personne values(104, 'Wilflol'       , 39, 'M', 'Mexique'    , 'Wespeed'            );
INSERT INTO personne values(105, 'Logicman'      , 36, 'F', 'Brésil'     , 'Hal Laboratory Inc.');
INSERT INTO personne values(106, 'Illumina'      , 36, 'F', 'Brésil'     , 'Hal Laboratory Inc.');
INSERT INTO personne values(107, 'Brash'         , 36, 'M', 'Chine'      , 'Bandai Namco'       );
INSERT INTO personne values(108, 'Cryptobazeo'   , 35, 'M', 'Chine'      , 'Bandai Namco'       );
INSERT INTO personne values(109, 'Draken'        , 33, 'M', 'Chine'      , 'Bandai Namco'       );
INSERT INTO personne values(110, 'Cheesy'        , 34, 'M', 'Chine'      , 'Bandai Namco'       );
INSERT INTO personne values(111, 'Jaoname'       , 46, 'M', 'Etats-Unis' , 'Cartoon Network'    );
INSERT INTO personne values(112, 'Loki'          , 45, 'M', 'Etats-Unis' , 'Cartoon Network'    );
INSERT INTO personne values(113, 'Luiyi'         , 22, 'F', 'Angleterre' , 'SK Gaming'          );
INSERT INTO personne values(114, 'Replays'       , 23, 'F', 'Angleterre' , 'SK Gaming'          );
INSERT INTO personne values(115, 'Toga'          , 23, 'F', 'Angleterre' , 'SK Gaming'          );
INSERT INTO personne values(116, 'Yuki'          , 29, 'M', 'Suède'      , 'Tribe'              );
INSERT INTO personne values(117, 'Mina'          , 32, 'F', 'Suède'      , 'Tribe'              );
INSERT INTO personne values(118, 'Pigmansly'     , 34, 'M', 'Suède'      , 'Tribe'              );
INSERT INTO personne values(119, 'Marinus'       , 37, 'M', 'France'     , 'Solary'             );
INSERT INTO personne values(120, 'Agus'          , 36, 'M', 'France'     , 'Solary'             );
INSERT INTO personne values(121, 'Anto'          , 25, 'M', 'France'     , 'Twitch'             );
INSERT INTO personne values(122, 'Flukely'       , 31, 'F', 'France'     , 'Twitch'             );
INSERT INTO personne values(123, 'Aizen'         , 30, 'F', 'France'     , 'Twitch'             );
INSERT INTO personne values(124, 'Rizu'          , 26, 'M', 'France'     , 'Twitch'             );
INSERT INTO personne values(125, 'Xel'           , 27, 'M', 'France'     , 'Twitch'             );
INSERT INTO personne values(126, 'Dejavu'        , 21, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(127, 'Aleria'        , 19, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(128, 'Eureka'        , 18, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(129, 'Unsociable'    , 28, 'F', 'Chine'      , 'Bing chilling'      );
INSERT INTO personne values(130, 'Gordon'        , 29, 'M', 'Chine'      , 'Bing chilling'      );
INSERT INTO personne values(131, 'Ramsey'        , 29, 'M', 'Chine'      , 'Bing chilling'      );
INSERT INTO personne values(132, 'Asvex'         , 28, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(133, 'Lonny'         , 27, 'F', 'Etats-Unis' , 'Gabaret'            );
INSERT INTO personne values(134, 'Wulpu'         , 32, 'F', 'Inde'       , 'Oreo'               );
INSERT INTO personne values(135, 'Zurikimo'      , 32, 'F', 'Inde'       , 'Oreo'               );
INSERT INTO personne values(136, 'Tayeb'         , 34, 'M', 'France'     , 'Rhinoshield'        );
INSERT INTO personne values(137, 'Apeiron'       , 36, 'M', 'France'     , 'Rhinoshield'        );
INSERT INTO personne values(138, 'Kat'           , 38, 'F', 'Etats-Unis' , 'In shape'           );
INSERT INTO personne values(139, 'Tibo'          , 32, 'M', 'Etats-Unis' , 'In shape'           );
INSERT INTO personne values(140, 'Tobi'          , 40, 'M', 'Etats-Unis' , 'In shape'           );
INSERT INTO personne values(141, 'Meuf'          , 39, 'F', 'Etats-Unis' , 'In shape'           );
INSERT INTO personne values(142, 'Jonne'         , 42, 'M', 'Etats-Unis' , 'Bing chilling'      );
INSERT INTO personne values(143, 'Senna'         , 42, 'M', 'Etats-Unis' , 'Bing chilling'      );
INSERT INTO personne values(144, 'Sun Tzu'       , 50, 'M', 'Chine'      , 'Bing chilling'      );